name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack and activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install workspace dependencies (hoisted)
        run: pnpm install -w

      - name: Cache web node_modules
        uses: actions/cache@v4
        with:
          path: apps/web/node_modules
          key: ${{ runner.os }}-web-modules-${{ hashFiles('apps/web/pnpm-lock.yaml', 'pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-web-modules-

      - name: Ensure web package deps are installed
        run: pnpm --filter ./apps/web install

      - name: Build web
        run: pnpm --filter ./apps/web build
