name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack and activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install workspace dependencies (hoisted)
        run: pnpm install -w

      - name: Ensure web package deps are installed
        run: pnpm --filter ./apps/web install

      - name: Build web
        run: pnpm --filter ./apps/web build
