name: prisma-migrate-deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install -w
      - name: Run Prisma migrations (deploy)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm -w dlx prisma migrate deploy --schema=./prisma/schema.prisma
